# Generated by Django 4.2.8 on 2024-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_image', models.ImageField(blank=True, default='empty_f.jpeg', null=True, upload_to='gold_coins')),
                ('coin_name', models.CharField(max_length=100)),
                ('coin_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
