# Generated by Django 4.2.8 on 2024-01-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
